### ISSUE TITLE
Test support for arm64

### ISSUE THREAD

**Issue by odidev** [Menziess/databricks-connect#4]
I want to test the compatibility of this package for arm64, but I did not get any test files in the repository. Could you please let me know if there is any other method to test this?

**Comment by Menziess** [comment]
I think you can run `databricks-connect test` to test the connection, or run `databricks-connect` to start an interactive shell to play around with the data on dbfs (in your workspace).

**Comment by odidev** [comment]
Hi @Menziess 
I have gone through it as per your suggestion and I also following [this](https://menziess.github.io/howto/install/databricks-connect/) but it's need configuration for databricks and I need below details for testing.
```
 Databricks Host:  
 Databricks Token: 
 Cluster ID:
 Org ID: 
 Port: 
```
Could you please share some pointers on databricks-connect configuration.

**Comment by Menziess** [comment]
All the information should be in the link that you posted.

If you go to your databricks cluster page, it'll have most of the information in the url:
![](https://menziess.github.io/images/install-databricks-connect/cluster-info.png)

You only need to create a token after that on your User Settings page.

Could you elaborate a bit more where you're stuck?
